apiVersion: v1
kind: Namespace
metadata:
  name: ns-app-template-core-backend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: ns-app-template-core-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-template-core-backend
  template:
    metadata:
      labels:
        app: app-template-core-backend
    spec:
      containers:
      - name: app-container
        image: ghcr.io/blrvio/template-core-backend-nodejs:development
        imagePullPolicy: Always
        env:
        - name: APM_ENABLED
          value: "true"

---

apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: ns-app-template-core-backend
spec:
  selector:
    app: app-template-core-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: ns-app-template-core-backend
spec:
  defaultBackend:
    service:
      name: app-service
      port:
        number: 80
