name: Build and Push Docker Image to prd environment

on:
  push:
    paths-ignore:
      - 'kube/**'
      - 'github/**'
    branches:
      - main

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

  security-tests:
    needs: test-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Trivy vulnerability scanner on project dependencies
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          exit-code: '1'
          trivy-config: trivy-hml.yaml

  push-and-notify:
    needs: security-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Dispatch Telegram Notification for Build Status
        if: ${{ always() }}
        env:
          TELEGRAM_TOKEN: ${{ secrets.MAIN_CHATOPS_TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.MAIN_CHATOPS_TELEGRAM_CHAT_ID }}
        run: |
          if [[ "${{ job.status }}" == "success" ]]; then
            MESSAGE="✅ **Success Notification:** The 'Build and Push' workflow executed on GitHub Actions has successfully completed without any errors. All steps and processes within the workflow were executed correctly. 🎉"
          else
            MESSAGE="⚠️ **Failure Alert:** The 'Build and Push' workflow executed on GitHub Actions has encountered an error and failed to complete. It's essential to inspect the detailed logs within GitHub Actions to diagnose the issue and address it promptly. 🚨"
          fi
          curl -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d parse_mode="Markdown" -d text="${MESSAGE}"
